language: python
# Can't use the simpler syntax yet for Python 3.7
# https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install .
script:
  - pytest
