language: python

# Can't use the simpler include syntax yet for Python 3.7:
# https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

install:
  # Install parachute
  # It seems that the only way for coverage.py to work, is to install parachute
  # in "editable" mode.
  - pip install -e .
  # Upgrade or install:
  # pytest -- Test runner
  # coverage -- Measure source code coverage of execution
  # pytest-cov -- Plugin for pytest to help run `coverage`
  # codecov -- Upload coverage report
  - pip install --upgrade pytest coverage pytest-cov codecov

script:
  - pytest --cov=src

after_success:
  - codecov
