language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

# Can't use the simpler include syntax yet for Python 3.7:
# https://github.com/travis-ci/travis-ci/issues/9815

install:

  - pip install -e .
  # Install our package. It seems that the only way to get coverage.py to work,
  # is to install parachute in "editable" mode.

  - pip install --upgrade
        pytest      # Test runner
        coverage    # Measures source lines coverage during execution
        pytest-cov  # Plugin for pytest to help run `coverage`
        codecov     # Uploads coverage report

script:
  - pytest --cov=src
  # Run test suite and measure execution coverage in the `src` directory.

after_success:
  - codecov
